import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Minified service worker auto-generated by @serwist/next — linting it
    // surfaces 80+ warnings from compressed code, drowning real signal.
    "public/sw.js",
    // One-off scripts under docs/ — not part of app surface.
    "docs/rich-menu/**",
    // gstack worktrees are scratch copies of the repo for parallel work;
    // linting them double-counts every issue from files we're not changing.
    ".claude/worktrees/**",
  ]),
]);

export default eslintConfig;
